### ISSUE TITLE
constant buffering when playing 128bit mp3 stream

### ISSUE THREAD

**Issue by K1WIZ** [thieu-b55/ESP32-audiokit-webradio-webinterface#2]
Tried playing a 128bit MP3 stream and constant buffering.  Unlistenable.

**Comment by thieu-b55** [comment]
sorry for the inconvenience but this program is only a user interface for the fantastic audio library                  https://github.com/schreibfaul1/ESP32-audioI2S 
I don't know which ESP32 you are using, from the ESP32 audiokit modules are different versions available, if you have one fitted with a ESP32WROOM without PSRAM then that could be the problem.
greetings,
thieu
