### ISSUE TITLE
Link issues with ESP32

### ISSUE THREAD

**Issue by AndreasMainz** [thieu-b55/ESP32-audiokit-webradio-webinterface#3]
I included all libs as rquired, using the newest ESP Core: V2.0.5 and get a lot of linker errors:

c:/users/admin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\Audio.cpp.o:(.literal._ZN5Audio17initializeDecoderEv+0x14): undefined reference to `AACDecoder_IsInit()'

c:/users/admin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\Audio.cpp.o:(.literal._ZN5Audio17initializeDecoderEv+0x18): undefined reference to `AACDecoder_AllocateBuffers()'

c:/users/admin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\Audio.cpp.o:(.literal._ZN5Audio15showCodecParamsEv+0x2c): undefined reference to `AACGetFormat()'

c:/users/admin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\Audio.cpp.o:(.literal._ZN5Audio15showCodecParamsEv+0x30): undefined reference to `AACGetID()'

c:/users/admin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\Audio.cpp.o:(.literal._ZN5Audio15showCodecParamsEv+0x34): undefined reference to `AACGetProfile()'

and many more..
What should i update?

**Comment by AndreasMainz** [comment]
I copied to AAC decoderfiles in the directory of the project..then linking was fine..

**Comment by thieu-b55** [comment]
hi Andreas,

I understand that you have solved the problem. I´m very glad for that, I
should not have known how you could solve the problem.
I hope everything works fine now and that you can enjoy the music.
sorry for my terrible english,
greetings and all the best for 2023,
thieu



Op wo 21 dec. 2022 om 11:31 schreef Andreas Mainz ***@***.***

**Comment by AndreasMainz** [comment]
Hello Thieu,Thank You ready much for your Reply, but I found out that my Audio Kit does not use 8333DAC but the old AC101. Do you know also a solution for this DAC?This Would be very helpful.Many thanks for your Reply and happy Christmas and Greetings for from GermanyAndreas KohlAm 22.12.2022 um 20:54 schrieb thieu-b55 ***@***.***>:﻿
hi Andreas,

I understand that you have solved the problem. I´m very glad for that, I
should not have known how you could solve the problem.
I hope everything works fine now and that you can enjoy the music.
sorry for my terrible english,
greetings and all the best for 2023,
thieu



Op wo 21 dec. 2022 om 11:31 schreef Andreas Mainz ***@***.***

**Comment by thieu-b55** [comment]
Hi Andreas,
in the github ESP-audioI2S library maybe you find the solution
https://github.com/schreibfaul1/ESP32-audioI2S/blob/master/examples/ESP32_A1S/ESP32_A1S.ino

But maybe the safest solution if you start a new build is go for a LyraT board it isn't expensive and you know what you buy,
which isn't always the case if you buy in China

greetings,
thieu-b55
Belgium

**Comment by AndreasMainz** [comment]
Hello thiem,Many 🙏, I got it to work..but in this sketch no web gui is provided. Do you have a recommendation for a nice gui with easy integration?BR from Germany Viele Grüße Andreas KohlAm 23.12.2022 um 08:29 schrieb thieu-b55 ***@***.***>:﻿
Hi Andreas,
in the github ESP-audioI2S library maybe you find the solution
https://github.com/schreibfaul1/ESP32-audioI2S/blob/master/examples/ESP32_A1S/ESP32_A1S.ino
greetings,
thieu-b55
Belgium

**Comment by thieu-b55** [comment]
Andreas change the beginning of the ESP32_webradio_audiokit.ino  see original (first) and chenged below. This should work

ORIGINAL from EP32_webradio_audiokit.ino

#include "Arduino.h"
#include "WiFi.h"
#include "Audio.h"
#include <SPI.h>
#include <Preferences.h>
#include "FS.h"
#include "SD.h"
#include <CSV_Parser.h>
#include <AsyncTCP.h>
#include <ESPAsyncWebServer.h>
#include "Wire.h"
#include "ES8388.h"

static ES8388 dac;                                 
int volume = 80;

Audio audio;
Preferences pref;
AsyncWebServer server(80);

#define SD_CS               13
#define SPI_MOSI            15
#define SPI_MISO             2
#define SPI_SCK             14

/*
 * Settings voor ESP32-A1S v2.2 (ES8388)
 * switch 2 & 3 ON
 *        1  4  5 OFF
 */
#define I2S_DSIN            26
#define I2S_BCLK            27
#define I2S_LRC             25
#define I2S_MCLK             0
#define I2S_DOUT            35

// I2C GPIOs
#define IIC_CLK             32
#define IIC_DATA            33

#define PA_EN               21

#define MAX_AANTAL_KANALEN  75


**************
CHANGE TO THIS
**************


#include "Arduino.h"
#include "WiFi.h"
#include "Audio.h"
#include <SPI.h>
#include <Preferences.h>
#include "FS.h"
#include "SD.h"
#include <CSV_Parser.h>
#include <AsyncTCP.h>
#include <ESPAsyncWebServer.h>
#include "Wire.h"
#include "AC101.h" //https://github.com/schreibfaul1/AC101

static AC101 dac;                                 
int volume = 80;

Audio audio;
Preferences pref;
AsyncWebServer server(80);

#define SD_CS               13
#define SPI_MOSI            15
#define SPI_MISO             2
#define SPI_SCK             14

/*
 * Settings voor ESP32-A1S v2.2 (ES8388)
 * switch 2 & 3 ON
 *        1  4  5 OFF
 */
// I2S GPIOs, the names refer on AC101, AS1 Audio Kit V2.2 2379
#define I2S_DSIN            25
#define I2S_BCLK            27
#define I2S_LRC             26
#define I2S_MCLK             0
#define I2S_DOUT            35


// I2C GPIOs
#define IIC_CLK             32
#define IIC_DATA            33

#define PA_EN               21

#define MAX_AANTAL_KANALEN  75

**Comment by thieu-b55** [comment]
I have posted a possible solution on github

Op vr 23 dec. 2022 om 13:22 schreef Andreas Mainz ***@***.***
