### ISSUE TITLE
Play mp3 on ESP32 LyraT.

### ISSUE THREAD

**Issue by Jefke1** [thieu-b55/ESP32-audiokit-webradio-webinterface#4]
First of all thanks for this code. 
Radio plays very well. But I can't get any sound from the mp3 player. 
i followed the instructions as described, put some mp3s in folder mp3_0, list is created, but when i confirm on mp3 player in the web interface, no sound. 
Tried with different sd cards and with different frequency settings. any suggestions are welcome.
ESP32 LyraT V4.3
Thank's in advance.

**Comment by thieu-b55** [comment]
Hello Jefke1,

For the moment no idea, can you connect your computer with the esp32 and open a terminal in the Arduino IDE while you are trying to play a mp3 file?  Maybe something shows up.
Maybe try to make a playlist again, remove first all the songlijstx folders. Connect then also the computer with the ESP32 and open a terminal in the arduino IDE
Maybe the mp3 files, it's just a guess, have you tried to play them in VLC or another media player?
Can you make a screen print from the SD card after making the playlist
How many mp3_x folders do you have with how many mp3 files?
Monday evening I'm going to do a test with my LyraT board and the program that's here on Github, maybe something is wrong. Tomorrow "het verhaal van vlaanderen" en "1985" on TV, sorry
I let you know if I find something.
greetings
thieu

**Comment by Jefke1** [comment]
Hi Thieu,
I get an error compiling the sketch, CSV ==>> NULL, trying to read an Arry with nothing in it. I've added some clippings.
Fijne zondag, geniet van uw TV moment, het is de moeite.
Grt, Jef.
![compile_warning](https://user-images.githubusercontent.com/47332797/218314324-3ee479d4-1e65-44b6-aecf-4891ffa490cc.PNG)
![K](https://user-images.githubusercontent.com/47332797/218314335-8972433e-af8c-4646-98ff-0af98a0a1e46.PNG)
![SD](https://user-images.githubusercontent.com/47332797/218314339-c6ad517b-dbb7-459f-97c2-4c2993c4438a.PNG)

**Comment by thieu-b55** [comment]
Hoi Jef

programma gedownload van github (zipfile)
inhoud SD kaart voor 1ste start met bestanden uit zip file SD card files gecopieerd naar SD kaart

![SD kaart begin](https://user-images.githubusercontent.com/99279324/218327988-a85562f9-8382-4b47-b4fe-2775b01ebdd9.png)
inhoud mp3_0  screenprint is gedeeltelijk totaal 90 mp3's
![inhoud mp3_0](https://user-images.githubusercontent.com/99279324/218328022-69c98556-576e-4126-b2d2-7f68f126f345.png)

programma met Arduino IDE in LyraT bord geprogrammeerd.
Na invullen WIFI gegevens en automatische restart gekozen mp3 lijst te maken
Na beeindigen mp3 lijst maken automatisch overgegaan naar mp3 speler.
SD kaart na mp3 lijst maken
![SD kaart na lijst maken](https://user-images.githubusercontent.com/99279324/218328188-3d5b06c0-c790-47a8-b1d0-c378c591c341.png)

inhoud songlijst0 (ook gedeeltelijk totaal 90 mp3's)
![inhoud songlijst0](https://user-images.githubusercontent.com/99279324/218328420-7f0ee5eb-6dc6-48b7-af44-98a940f726f1.png)

screenprint na mp3 inlezen
![na inlezen mp3](https://user-images.githubusercontent.com/99279324/218328258-847e0816-b07c-4a0b-a546-b7c47dec6b07.png)

programma doet hier wat het moet doen.
gr thieu

**Comment by Jefke1** [comment]
Hoi Thieu,
Bedankt voor je snelle reactie, ik heb alles vanaf het begin en volgens de richtlijnen uitgevoerd.
Nog steeds zonder resultaat, radio speelt zeer goed, mp3 nog niet gelukt, als ik mp3 spelen kies blijft het programma ergens
hangen. Ik kan dan ook niet terug naar de webradio zonder te resetten. Ik ga proberen eens uit te zoeken waar het bij mij hapert. Ik laat iets weten als ik resultaat heb.
Met vriendelijke groeten,
Jef.

**Comment by thieu-b55** [comment]
Jef,

heb je al eens andere mp3 files geprobeerd. Geen idee of dat de oplossing is, maar proberen kost niets.

succes en laat iets weten als je iets gevonden hebt,
thieu

**Comment by Jefke1** [comment]
Hey Thieu,
Heb ik al geprobeerd, heb ook verschillende files gemaakt mp3_0, mp3_1 enz ...
Maakt zonder problemen de lijsten ==>> stapt dan over naar mp3 speler, wanneer ik bevestig met OK, in de webinterface zie ik mp3 speler, maar geen geluid en dan moet ik resetten. mp3 speler stoppen komt niet te voorschijn.
Grt, Jef

**Comment by thieu-b55** [comment]
Jef,

mp3 speler stoppen is er niet, terug een internetradio selecteren en op OK drukken.
Het audio decoder gedeelte voor zowel internetradio als mp3 files heb ik niet geschreven (beetje veel boven mijn software capaciteiten). als je daar meer over wil weten zie link hier beneden.

https://github.com/schreibfaul1/ESP32-audioI2S/wiki

gr,
thieu

je mp3 files zijn die allemaal gecomprimeerd met dezelfde mp3 encoder, probeer dan eens een andere, het is maar een idee
Zet het volume eens op maximum
